### ISSUE TITLE
Sponsorship Cancellation Not Pro-rated

### ISSUE THREAD

**Issue by fmckeogh** [fasterthanlime/feedback#129]
Hi!

It appears access to Silver+ tier content appears to stop immediately after GitHub sponsorship is cancelled, rather than at the end of the billing period. Since the sponsorship amount is not refunded pro rata technically sponsors are losing out. However I may be misunderstanding the billing process, my apologies if that's the case!

Thanks!

**Comment by fasterthanlime** [comment]
Aw, I'm sorry I'm seeing this only 14 days after you reported it (I'm still trying to figure out why I don't actually get notification e-mails for this repository..).

I reviewed the GraphQL query I use for this, you can try it for yourself in the GitHub GraphQL Explorer:

```graphql
{
  viewer {
    databaseId
    login
    name
    avatarUrl
  }
  user(login: "fasterthanlime") {
    sponsorshipForViewerAsSponsor {
      tier {
        isOneTime
        monthlyPriceInDollars
      }
    }
  }
}
```

...does that show anything for you? If not, I'll float it up to the GitHub Sponsors team, because it sounds like their bug.

I don't think I have control over refunds (but I can double check), is there any other way I can make this right for you (besides looking into it)?

**Comment by fasterthanlime** [comment]
I'm really confused because that response should give you access to silver content. 

Can you try visiting https://fasterthanli.me/debug-credentials ?

Also, can you try logging in again on fasterthanli.me ? Eventually I should set up github webhooks, but for now they're not set up, so.. is it possible you first logged in with GitHub without being a sponsor and it just never refreshed ?

**Comment by fmckeogh** [comment]
<img width="919" alt="Screenshot 2022-12-07 at 22 43 04" src="https://user-images.githubusercontent.com/8290136/206407635-e6f096bd-1dd0-4da8-b4bd-8dbdfb3c1443.png">

I clicked log in multiple times and got the above message.

I then cleared all website data, and on GitHub resubscribed and then cancelled again, and now it's working 😅

Sorry for wasting your time!

**Comment by fasterthanlime** [comment]
Huh, I really need to get on this webhook thing! Thanks for reporting and testing this, and glad it eventually worked out!
