### ISSUE TITLE
video progress bar on smartphone not accessible

### ISSUE THREAD

**Issue by Mcdostone** [fasterthanlime/feedback#151]
Hi,

Small feedback regarding your video player: the video progress bar is difficult to reach on a smartphone.

Device: OnePlus 6, android 11

https://fasterthanli.me/videos/we-need-to-talk-about-dropout
![signal-2023-01-04-145928_002](https://user-images.githubusercontent.com/6984659/210572073-9d356eff-d819-4f06-8ad5-9a386148e16c.jpeg)

**Comment by fasterthanlime** [comment]
The tap target is much larger (taller) than it would appear at first, so it's not _that_ bad on my phone at least — that UI was pretty much modelled after YouTube for Android's interface (which has been changed since..). I might go ahead and move the seek bar above the time / fullscreen controls in a later release.

**Comment by fasterthanlime** [comment]
I've retired my video platform for the time being, so I'm closing this!
