### ISSUE TITLE
Open source H264 encoder

### ISSUE THREAD

**Issue by jasikpark** [fasterthanlime/feedback#79]
- https://github.com/cisco/openh264
- https://www.openh264.org/
- http://blogs.cisco.com/collaboration/open-source-h-264-removes-barriers-webrtc (https://web.archive.org/web/20140721062127/http://blogs.cisco.com/collaboration/open-source-h-264-removes-barriers-webrtc/)
- https://blog.mozilla.org/blog/2013/10/30/video-interoperability-on-the-web-gets-a-boost-from-ciscos-h-264-codec

I realize now that this was started in 2013, so it probably doesn't materially change whether you can use it to encode h264 video for your platform? But it's kinda cool :)

I seemed to remember something about not supporting h264 b/c of licensing costs for your video platform

**Comment by fasterthanlime** [comment]
Thanks! I am aware of openh264, however I believe the problem is not really encoding videos themselves, it's streaming videos to users _that pay for it_. I'm in a weird situation where folks don't pay _to see the videos_ per se, but folks who donate money do get to see some videos 1 week in advance, so... I'd rather be on the safe side here.

I do encode to H.264 for iPhones, but that's a small fraction of traffic - if/when it becomes big enough to qualify for royalty payment, I'll worry about it :)

(Also, my impression is that openh264 is inferior to x264 in a bunch of ways. But thanks for linking it anyway, I appreciate the intention!)
