### ISSUE TITLE
Request for clarification on Rust intro

### ISSUE THREAD

**Issue by kubycsolutions** [fasterthanlime/feedback#88]
Many thanks for https://fasterthanli.me/articles/a-half-hour-to-learn-rust; I'm going through it now.

Question, though: When you introduce Self, the code example includes the statement
`   type Output = Self;`
 ... but then never explicitly references Output. Should that perhaps have read something like the following? If not, you should probably clarify what the intended meaning actually is.
 
 ```
impl std::ops::Neg for Number {
    type Output = Self;

    fn neg(self) -> Output {
        Output {
            value: -self.value,
            odd: self.odd,
        }        
    }
}
```

**Comment by fasterthanlime** [comment]
> ... but then never explicitly references Output.

So, that's a matter of style, this could also be written like so:

```rust
impl std::ops::Neg for Number {
   type Output = Self;

   fn neg(self) -> Self::Output {
       Output {
           value: -self.value,
           odd: self.odd,
       }        
   }
}
```

But the `type Output = Self` here isn't just "because it's convenient" (why you'd normally declare type aliases). It's part of the signature of [the Neg trait](https://doc.rust-lang.org/stable/std/ops/trait.Neg.html) so we _have_ to set it to something.
